// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.Domain;

#nullable disable

namespace Parking.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712171501_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Parking.Domain.Abstractions.Models.ParkingValues", b =>
                {
                    b.Property<Guid>("ParkingValuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("HalfInTheFirstHour")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("HourlyTolerance")
                        .HasColumnType("int");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParkingValuesId");

                    b.ToTable("ParkingValues");
                });

            modelBuilder.Entity("Parking.Server.Abstractions.Models.Parkings", b =>
                {
                    b.Property<Guid?>("ParkingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Plate")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParkingsId");

                    b.ToTable("Parkings");
                });
#pragma warning restore 612, 618
        }
    }
}
